# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: RheaPrad/website

media_folder: src/lib/content
public_folder: /src/lib/content

collections:
  - name: books
    label: Books
    folder: src/lib/content/art-page/books
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - {
          label: Format,
          name: format,
          widget: string,
          hint: "e.g. Children's Picturebook | 5.75 x 7.75 in",
        }
      - { label: Cover Image, name: cover_image, widget: image }
      - {
          label: Gallery,
          name: gallery,
          widget: list,
          field: { label: Image, name: image, widget: image },
        }
      - { label: Description, name: body, widget: markdown }

  - name: comics
    label: Comics
    folder: src/lib/content/art-page/comics
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }

  - name: blog
    label: Blog
    folder: src/lib/content/blog-page
    create: true
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string, required: false }
      - { label: Date, name: date, widget: datetime }
      - {
          label: Description,
          name: description,
          widget: string,
          required: false,
        }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown, required: false }

  - name: home
    label: Home
    files:
      - name: home
        label: Home Page
        file: src/lib/content/home-page/home.md
        fields:
          - { label: Featured Book Cover, name: featured_book, widget: image }
          - { label: Featured Comic Cover, name: featured_comic, widget: image }

  - name: about
    label: About
    files:
      - name: about
        label: About Page
        file: src/lib/content/about-page/about.md
        fields:
          - { label: Photo, name: photo, widget: image }
          - {
              label: LinkedIn URL,
              name: linkedin,
              widget: string,
              required: false,
            }
          - { label: Email, name: email, widget: string, required: false }
          - {
              label: Instagram URL,
              name: instagram,
              widget: string,
              required: false,
            }
          - {
              label: BlueSky URL,
              name: bluesky,
              widget: string,
              required: false,
            }
          - { label: Bio, name: body, widget: markdown }
